from enum import Enum, auto

class NodeType(Enum):
    ROOT = auto()
    METHOD = auto()
    PARAMETER_LIST = auto()
    PARAMETER = auto()
    IDENTIFIER = auto()
    RETURN = auto()
    RETURN_TYPE = auto()
    TYPE = auto()
    STATEMENT_LIST = auto()
    STATEMENT = auto()
    EXPRESSION = auto()
    DEFINITION = auto()
    CONDITIONAL = auto()
    ELSE = auto()
    TERM = auto()
    WHILE_LOOP = auto()
    METHOD_CALL = auto()
    UNARY_OPERATION = auto()
    BINARY_OPERATION = auto()
    OPERATION = auto()
    ASSIGN = auto()